### ISSUE TITLE
pulse generator

### ISSUE THREAD

**Issue by kzali** [G-EDM/G-EDM#2]
Is this project abandoned? and I cannot find the schematics of the pulse generator.  I am new here so pardon me if I am missing something

**Comment by G-EDM** [comment]
If you check the youtube channel and the community section you can get some fresh updates on the projects current status. There is heavy development going on. I just ordered new PCB prototypes and spend days soldering stuff.

https://www.youtube.com/@G-EDM/community

The schematics itself is not yet released. The new boards need approval first.  You can contact me via email if you're interested in the files. goblin-dev@proton.me

Once the new boards are tested and working I may upload some files.

**Comment by kzali** [comment]
Thanks for this quick respone.  Great work.  I will wait for your upload.  I dont have a job right now but will donate as soon as I am able to

**Comment by G-EDM** [comment]
Good to hear. I'm happy about every cup of free coffee. Can't tell yet how long it takes but things move as fast as possible.

**Comment by G-EDM** [comment]
https://github.com/G-EDM/GEDM-EVO2-CNC/tree/main/files/schematics-and-gerbers
